version: "3.9"
services:
  ssmp-server:
    image: ghcr.io/ccmbioinfo/ssmp:dev
    init: true
    environment:
      TEST_NODE_URL:
      KEYCLOAK_AUTH_URL:
      KEYCLOAK_REALM:
      KEYCLOAK_CLIENT_ID:
      NODE_ENV: development
      G4RD_USERNAME:
      G4RD_PASSWORD:
      G4RD_URL:
      MONGO_CONNECTION_STRING:
    ports:
      - 3000:3000
    logging:
      driver: journald
    networks:
      - ssmp-dev
networks:
  ssmp-dev:
    driver: bridge
