version: "3.9"
services:
  ssmp-server:
    image: ghcr.io/ccmbioinfo/ssmp:dev
    environment:
      TEST_NODE_URL: ${TEST_NODE_URL}
      KEYCLOAK_AUTH_URL: ${KEYCLOAK_AUTH_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      NODE_ENV: development
      PT_AUTH0_CLIENT_ID: ${PT_AUTH0_TOKEN_CLIENT_ID}
      PT_AUTH0_CLIENT_SECRET: ${PT_AUTH0_TOKEN_CLIENT_SECRET}
      PT_AUTH0_TOKEN_ENDPOINT: ${PT_AUTH0_TOKEN_ENDPOINT}
      PT_ENDPOINT: ${TEST_NODE_URL}
    ports:
      - 3000:3000
    logging:
      driver: journald
    networks:
      - ssmp-dev
networks:
  ssmp-dev:
    driver: bridge
