version: "3.9"
services:
  react:
    image: node:16-slim
    user: node
    working_dir: /usr/src/app
    init: true
    command: yarn start
    ports:
      - ${STORYBOOK_PORT:-6006}:6001
      - ${REACT_PORT}:3000
    volumes:
      - ./react:/usr/src/app
    environment:
      REACT_APP_GRAPHQL_URL:
      REACT_APP_KEYCLOAK_AUTH_URL: ${REACT_APP_KEYCLOAK_FRONT_END_AUTH_URL}
      REACT_APP_KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      REACT_APP_KEYCLOAK_CLIENT_ID: ${KEYCLOAK_REACT_CLIENT_ID}
      REACT_APP_SOURCE_LIST:
  ssmp-server:
    build:
      context: server
      target: dev
    image: ghcr.io/ccmbioinfo/ssmp:dev
    init: true
    command: yarn start
    ports:
      - ${SSMP_SERVER_PORT}:3000
    volumes:
      - ./server:/usr/src/app
    environment:
      G4RD_AUTH_METHOD:
      G4RD_CLIENT_ID:
      G4RD_GRANT_TYPE:
      G4RD_PASSWORD:
      G4RD_REALM:
      G4RD_TOKEN_URL:
      G4RD_URL:
      G4RD_USERNAME:
      KEYCLOAK_AUTH_URL:
      KEYCLOAK_REALM:
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_SERVER_CLIENT_ID}
      NODE_ENV: development
      TEST_NODE_URL:
      TEST_NODE_OAUTH_ACTIVE:
      TEST_NODE_SSMP_TOKEN_CLIENT_ID:
      TEST_NODE_SSMP_TOKEN_CLIENT_SECRET:
      TEST_NODE_SSMP_TOKEN_ENDPOINT:
      TEST_NODE_TOKEN_AUDIENCE:
      MONGO_CONNECTION_STRING: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo/${MONGO_INITDB_DATABASE}?authSource=admin
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_DATABASE:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - ${MONGO_INITDB_PORT}:27017
    volumes:
      - ./mongo/data:/data/db
  test-node-1:
    image: node:16-slim
    user: node
    working_dir: /usr/src/app
    init: true
    command: yarn start
    ports:
      - ${TEST_NODE_PORT}:3000
    volumes:
      - ./test-node:/usr/src/app
    environment:
      TEST_NODE_TOKEN_ISSUER:
      TEST_NODE_TOKEN_AUDIENCE:
      TEST_NODE_OAUTH_ACTIVE:
      TEST_DATA_DB:
      TEST_DATA_DB_PORT:
      TEST_DATA_DB_HOST:
      TEST_DATA_DB_USER:
      TEST_DATA_DB_PASSWORD:
  stager-mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_DATABASE: "${TEST_DATA_DB}"
      MYSQL_USER: "${TEST_DATA_DB_USER}"
      MYSQL_PASSWORD: "${TEST_DATA_DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${TEST_DATA_DB_ROOT_PASSWORD}"
    ports:
      - ${TEST_DATA_DB_PORT}:3306
    volumes:
      - ${TEST_DATA_DATA_VOLUME}:/var/lib/mysql
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0-legacy
    environment:
      KEYCLOAK_SERVER_CLIENT_ID:
      KEYCLOAK_REACT_CLIENT_ID:
      KEYCLOAK_CLIENT_ID:
      KEYCLOAK_USER:
      KEYCLOAK_PASSWORD:
      KEYCLOAK_PORT:
      KEYCLOAK_REALM:
      DB_VENDOR: H2
      REACT_URL:
      AUTH0_BROKER_AUTH_URL: ${TEST_NODE_TOKEN_ISSUER}authorize
      AUTH0_BROKER_TOKEN_URL: ${TEST_NODE_TOKEN_ISSUER}oauth/token
      AUTH0_BROKER_CLIENT_ID: ${KEYCLOAK_AUTH0_CLIENT_ID}
      AUTH0_BROKER_CLIENT_SECRET: ${KEYCLOAK_AUTH0_CLIENT_SECRET}
    ports:
      - ${KEYCLOAK_PORT}:8080
    volumes:
      - ./keycloak/scripts:/usr/scripts
      - ./keycloak/scripts/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
      - ./keycloak/theme/ssmp:/opt/jboss/keycloak/themes/ssmp
