version: "3.9"
services:
  react:
    image: node:16.3-buster
    volumes:
      - ./react:/usr/app
    environment:
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
      REACT_APP_API_PORT: ${REACT_APP_API_PORT}
      REACT_APP_KEYCLOAK_AUTH_URL: ${REACT_APP_KEYCLOAK_FRONT_END_AUTH_URL}
      REACT_APP_KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      REACT_APP_KEYCLOAK_CLIENT_ID: ${KEYCLOAK_REACT_CLIENT_ID}
    ports:
      - ${STORYBOOK_PORT:-6006}:6001
      - ${REACT_PORT}:3000
    working_dir: /usr/app
    user: "1000" #node
    entrypoint: "yarn start"
    networks:
      - ssmp

  ssmp-server:
    image: node:16.3-buster
    environment:
      KEYCLOAK_AUTH_URL: ${KEYCLOAK_AUTH_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      SERVER_PORT: ${SSMP_SERVER_PORT}
      NODE_ENV: ${NODE_ENV}
      TEST_NODE_SSMP_TOKEN_CLIENT_ID: ${TEST_NODE_SSMP_TOKEN_CLIENT_ID}
      TEST_NODE_SSMP_TOKEN_CLIENT_SECRET: ${TEST_NODE_SSMP_TOKEN_CLIENT_SECRET}
      TEST_NODE_SSMP_TOKEN_ENDPOINT: ${TEST_NODE_SSMP_TOKEN_ENDPOINT}
      TEST_NODE_OAUTH_ACTIVE: ${TEST_NODE_OAUTH_ACTIVE}
      TEST_NODE_TOKEN_AUDIENCE: ${TEST_NODE_TOKEN_AUDIENCE}
    user: "1000" #node
    working_dir: /usr/app
    ports:
      - ${SSMP_SERVER_PORT}:${SSMP_SERVER_PORT}
    volumes:
      - ./server:/usr/app
    entrypoint: "yarn start-dev"
    networks:
      - ssmp

  test-node-1:
    image: node:16.3-buster
    environment:
      SERVER_PORT: ${TEST_NODE_PORT}
      TEST_NODE_TOKEN_ISSUER: ${TEST_NODE_TOKEN_ISSUER}
      TEST_NODE_TOKEN_AUDIENCE: ${TEST_NODE_TOKEN_AUDIENCE}
      TEST_NODE_OAUTH_ACTIVE: ${TEST_NODE_OAUTH_ACTIVE}
    user: "1000" #node
    working_dir: /usr/app
    ports:
      - ${TEST_NODE_PORT}:${TEST_NODE_PORT}
    volumes:
      - ./test-node:/usr/app
    entrypoint: "yarn start-dev"
    networks:
      - ssmp

  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    environment:
      KEYCLOAK_SERVER_CLIENT_ID: ${KEYCLOAK_SERVER_CLIENT_ID}
      KEYCLOAK_REACT_CLIENT_ID: ${KEYCLOAK_REACT_CLIENT_ID}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_PORT: ${KEYCLOAK_PORT}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      REACT_PORT: ${REACT_PORT}
    ports:
      - ${KEYCLOAK_PORT}:8080
    volumes:
      - ./keycloak/scripts:/usr/scripts
      - ./keycloak/theme/ssmp:/opt/jboss/keycloak/themes/ssmp
      - ./keycloak/config/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
    networks:
      - ssmp

networks:
  ssmp:
    driver: bridge
