version: "3.9"
services:
  react:
    image: node:16.3-buster
    volumes:
      - ./react:/usr/app
    environment:
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
      REACT_APP_API_PORT: ${REACT_APP_API_PORT}
    ports:
      - ${STORYBOOK_PORT:-6006}:6001
      - ${REACT_PORT}:3000
    working_dir: /usr/app
    user: "1000" #node
    entrypoint: "yarn start"
    networks:
      - ssmp

  ssmp-server:
    image: node:16.3-buster
    environment:
      SERVER_PORT: ${SSMP_SERVER_PORT}
    user: "1000" #node
    working_dir: /usr/app
    ports:
      - ${SSMP_SERVER_PORT}:${SSMP_SERVER_PORT}
    volumes:
      - ./server:/usr/app
    entrypoint: "yarn start-dev"
    networks:
      - ssmp

networks:
  ssmp:
    driver: bridge
