version: "3.9"

x-common: &common
  restart: unless-stopped
  logging:
    driver: journald

services:
  server:
    build: server
    image: ghcr.io/ccmbioinfo/osmp:latest
    cpus: 1.0
    mem_limit: 5G
    restart: always
    environment:
      G4RD_AUTH_METHOD:
      G4RD_PASSWORD:
      G4RD_URL:
      G4RD_USERNAME:
      G4RD_REALM:
      G4RD_GRANT_TYPE:
      G4RD_TOKEN_URL:
      G4RD_CLIENT_ID:
      KEYCLOAK_AUTH_URL:
      KEYCLOAK_CLIENT_ID:
      KEYCLOAK_REALM:
      MONGO_CONNECTION_STRING:
      SERVER_SESSION_SECRET:
      TEST_NODE_URL: http://test-node:3000/data
    ports:
      - 3000:3000
    <<: *common

  test-node:
    build: test-node
    image: ghcr.io/ccmbioinfo/osmp-test-node
    environment:
      TEST_DATA_DB:
      TEST_DATA_DB_PORT: 3306
      TEST_DATA_DB_HOST: test-node-mysql
      TEST_DATA_DB_USER:
      TEST_DATA_DB_PASSWORD:
    <<: *common

  test-node-mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "${TEST_DATA_DB}"
      MYSQL_USER: "${TEST_DATA_DB_USER}"
      MYSQL_PASSWORD: "${TEST_DATA_DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${TEST_DATA_DB_ROOT_PASSWORD}"
    volumes:
      - ${PROJECT_ROOT:-.}/test_node_db_data:/var/lib/mysql
    <<: *common

  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0-legacy
    environment:
      KEYCLOAK_USER:
      KEYCLOAK_PASSWORD:
      KEYCLOAK_REALM:
      DB_VENDOR: mysql
      DB_ADDR: "${KEYCLOAK_DB_ADDR}"
      DB_DATABASE: "${KEYCLOAK_DB}"
      DB_USER: "${KEYCLOAK_DB_USER}"
      DB_PASSWORD: "${KEYCLOAK_DB_PASSWORD}"
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_FRONTEND_URL: "https://keycloak.ccmdev.ca/auth"
      AUTH0_BROKER_TOKEN_URL: ${G4RD_TOKEN_URL}
      AUTH0_BROKER_MANAGEMENT_API_URL: ${G4RD_AUTH0_BASE_URL}api/v2/
      AUTH0_BROKER_CLIENT_ID: ${G4RD_CLIENT_ID}  # use same creds as osmp server backend
      AUTH0_BROKER_USERNAME: ${G4RD_USERNAME}
      AUTH0_BROKER_PASSWORD: ${G4RD_PASSWORD}
      AUTH0_GRANT_TYPE: ${G4RD_GRANT_TYPE}
    ports:
      - 8080:8080
    <<: *common
