name: "Node: build and push development image"
on:
  push:
    branches:
      - develop
    paths:
      - .github/workflows/node.yml
      - server/**
  pull_request:
    branches:
      - develop
    paths:
      - .github/workflows/node.yml
      - server/**

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build development image
        uses: docker/build-push-action@v2
        with:
          context: server
          target: BUILD_IMAGE
          load: true
          tags: test-image
          pull: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Run eslint
        if: github.event_name == 'pull_request'
        run: |
          docker run --rm test-image yarn lint

      - name: Run prettier
        if: github.event_name == 'pull_request'
        run: |
          docker run --rm test-image yarn format

      - name: Log in to registry
        uses: docker/login-action@v1
        if: github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push development image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: server
          target: DEPLOY_IMAGE
          push: true
          tags: ghcr.io/ccmbioinfo/ssmp:dev
