name: "Build react app and upload to Minio"
on:
  pull_request:
    branches:
      - develop
    paths:
      - .github/workflows/react.yml
      - react/src/**/*


# Testing with hardcoded values, will change these to environmental secrets
env:
  REACT_APP_GRAPHQL_URL: http://localhost:4777/graphql
  REACT_APP_KEYCLOAK_AUTH_URL: http://localhost:9821/auth
  REACT_APP_KEYCLOAK_REALM: ssmp
  REACT_APP_KEYCLOAK_CLIENT_ID: ssmp-app

jobs:
  build-react:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: react
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install dependencies
        run: yarn install
      - name: run eslint
        run: |
          yarn lint
      - name: run prettier
        run: |
          yarn format
      - name: compile typescript
        run: |
          yarn tsc
      - name: Generate build
        run: yarn build
      - name: Upload to Minio bucket
        # Uncomment during actual deploy to dev server
        if: github.event_name == 'push' 
        environment: SSMP_BUILD 
        env:
          MC_HOST_minio: ${{ secrets.MC_HOST }}
        run: |
          sudo curl --output /usr/local/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc
          sudo chmod +x /usr/local/bin/mc
          ./deploy.sh minio ${{ secrets.MINIO_BUCKET }}
