name: "Build react app and upload to Minio"
on:
  pull_request:
    branches:
      - develop
    paths:
      - .github/workflows/react.yml
      - react/src/**/*

jobs:
  build-react:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: react
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dependencies
        run: yarn install
      - name: Generate build
        run: yarn build
      - name: Upload to Minio bucket
        run: bash deploy.sh minio ssmp-site-dev.minio.genomics4rd.ca